spring:
  datasource:
    url: jdbc:h2:file:./database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 1
    dashboard:
      enabled: false
runtime:
  fiji-path: 'fiji-bin/Fiji.app'
  fiji-executable-path: 'fiji-bin/Fiji.app/ImageJ-linux64'
  fiji-wrapper: '/usr/bin/xvfb-run'

