name: jipipe_growth_assay_webapp
volumes:
  jipipe_growth_assay_webapp_data:
services:
  webapp:
    build: .
    restart: always
    ports:
      - "8193:8080"
    depends_on:
      -  mariadb
    environment:
    # Context path (deploying the app)
      SERVER_SERVLET_CONTEXT_PATH: '/jipipe-growth-analysis-webapp'
    # Memory for Fiji (8G = 8GB)
      RUNTIME_FIJI_ARGS_1: 8G
    # Maximum number of background jobs
      ORG_JOBRUNR_BACKGROUND_JOB_SERVER_WORKER_COUNT: 4
    # Maximum image size for uploads
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
    # Root admin credentials
      ACCOUNTS_ADMIN_USERNAME: 'admin@webapp'
      ACCOUNTS_ADMIN_PASSWORD: 'TZ6ZM2nmREUNyfya'
    # Database config
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/jipipe_web"
      SPRING_DATASOURCE_USERNAME: jipipe_web
      SPRING_DATASOURCE_PASSWORD: lBpuJweTQWGhvr0o
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MariaDBDialect"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
    # Data config
      RUNTIME_CUSTOM_TEMP_DIRECTORY: /webapp_data
    volumes:
      - jipipe_growth_assay_webapp_data:/webapp_data
  mariadb:
    image: "mariadb:latest"
    restart: always
    expose:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jipipe_web
      MYSQL_USER: jipipe_web
      MYSQL_PASSWORD: lBpuJweTQWGhvr0o
      MYSQL_ROOT_PASSWORD: ngek9RlN1BS3K82i
    volumes:
      - jipipe_growth_assay_webapp_data:/var/lib/mysql
    
