/*
 * Copyright (c) 2026.
 *
 * Research Group Applied Systems Biology - Head: Prof. Dr. Marc Thilo Figge
 * https://www.leibniz-hki.de/en/applied-systems-biology.html
 * HKI-Center for Systems Biology of Infection
 * Leibniz Institute for Natural Product Research and Infection Biology - Hans Knöll Institute (HKI)
 * Adolf-Reichwein-Straße 23, 07745 Jena, Germany
 *
 * The project code is licensed under MIT.
 * See the LICENSE file provided with the code for the full license.
 */

/*
  WARNING: DO NOT MODIFY OR DELETE
  This file is auto-generated by Quasar CLI
  It's recommended to NOT .gitignore it
  You don't have to use TypeScript in your project, don't worry
*/
import 'quasar/dist/types/feature-flag.d.ts';

declare module 'quasar/dist/types/feature-flag.d.ts' {
  interface QuasarFeatureFlags {
    store: true;
  }
}
