server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./storage/database
    username: sa
    password: password
    driverClassName: org.h2.Driver
#    url: 'jdbc:mariadb://localhost:3306/jast-dev'
#    username: jast-dev
#    password: jast
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 2
    dashboard:
      enabled: true
runtime:
  fiji-path: 'bin/jipipe-linux'
  fiji-executable-path: 'bin/jipipe-linux/ImageJ-linux64'
  fiji-args: [ '--memory', '8G' ]
  fiji-wrapper-enabled: true
  fiji-wrapper: '/usr/bin/xvfb-run'
  fiji-wrapper-args: [ '-a' ]
  custom-temp-directory: "./storage/tmp"
  data-directory: "./storage/data"
  shared-resources-directory: "./share"
  keep-tmp: true
  system-packages:
      -
        operating-system: "linux"
        must-exist: "/usr/bin/R"
        key: [ "settings", "org.hkijena.jipipe:r", "project-default-environment" ]
        value: '{ "content" : { "load-from-artifact" : false, "arguments" : { "expression" : "ARRAY(script_file)" }, "r-executable-path" : "/usr/bin/R", "rscript-executable-path" : "/usr/bin/Rscript" }, "enabled" : true }'
      -
        operating-system: "linux"
        must-exist: "/usr/bin/tesseract"
        key: [ "settings", "org.hkijena.jipipe:r", "org.hkijena.jipipe:ij-ocr" ]
        value: '{ "content" : { "load-from-artifact" : false, "arguments" : { "expression" : "cli_parameters" }, "executable-path" : "/usr/bin/tesseract" }, "enabled" : true }'
  prefer-system-packages: true
  verbose: true
provider:
  provider-name: 'Localhost'
  provider-url: 'http://localhost'
  imprint-file: ''
  privacy-statement-file: ''
accounts:
  admin-username: 'admin@localhost'
  admin-password: 'Ckw55ryzy1mXGxb8'
security:
  jwt-secret: "8TJGD0tLb0M20pxRyasR3ajktjYVfhzqVauIleiKfRJdy3SVKr95JYpC7enixXeD"
  jwt-access-token-expiration-in-minutes: 60
  jwt-refresh-token-expiration-in-minutes: 1440
#server:
#  servlet:
#    context-path: '/abc'
debug: off

