server:
  port: 8081
spring:
  datasource:
    #    url: jdbc:h2:file:./storage/database
    #    username: sa
    #    password: password
    #    driverClassName: org.h2.Driver
    url: 'jdbc:mariadb://localhost:3306/jast-dev'
    username: jast-dev
    password: jast
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 2
    dashboard:
      enabled: true
runtime:
  fiji-path: 'bin/jipipe-linux'
  fiji-executable-path: 'bin/jipipe-linux/ImageJ-linux64'
  fiji-args: [ '--memory', '8G' ]
  fiji-wrapper-enabled: true
  fiji-wrapper: '/usr/bin/xvfb-run'
  fiji-wrapper-args: [ '-a' ]
  custom-temp-directory: "./storage/tmp"
  data-directory: "./storage/data"
  shared-resources-directory: "./share"
  keep-tmp: true
accounts:
  admin-username: 'admin@localhost'
  admin-password: 'Ckw55ryzy1mXGxb8'
security:
  jwt-secret: "8TJGD0tLb0M20pxRyasR3ajktjYVfhzqVauIleiKfRJdy3SVKr95JYpC7enixXeD"
  jwt-access-token-expiration-in-minutes: 60
  jwt-refresh-token-expiration-in-minutes: 1440
#server:
#  servlet:
#    context-path: '/abc'
debug: off

